// emoji → 图标文件名映射。生成图片放入 public/icons/<name>.png 后自动生效。
// 图片缺失时 Icon 组件回退为原 emoji，不会破图。
export const EMOJI_TO_NAME: Record<string, string> = {
  '💡': 'bulb',
  '🎯': 'target',
  '🃏': 'joker',
  '🔥': 'fire',
  '🎓': 'graduation',
  '🎉': 'party',
  '👑': 'crown',
  '📖': 'book',
  '💰': 'coins',
  '✅': 'check',
  '❌': 'cross',
  '←': 'arrow-left',
  '→': 'arrow-right',
  '👇': 'arrow-down',
  '🥉': 'medal-bronze',
  '⚪': 'medal-silver',
  '🥇': 'medal-gold',
  '💎': 'gem',
  '💠': 'gem-blue',
  '🌟': 'star',
  '🦊': 'fox',
  '🐷': 'pig',
  '🪨': 'rock',
  '⚖️': 'scale',
  '⚖': 'scale',
  '♠': 'spade',
  '♥': 'heart',
  '♦': 'diamond',
  '♣': 'club',
  '🂡': 'cards',
  '📏': 'ruler',
  '🏠': 'house',
  '🎁': 'gift',
  '📊': 'bar-chart',
  '🌱': 'seedling',
  '⚡': 'zap',
  '📍': 'pin',
  '🤖': 'robot',
  '🫘': 'beans',
  '🔄': 'refresh',
  '🏆': 'trophy',
  '📒': 'book2',
  '⚠️': 'warn',
  '⚠': 'warn',
  '👥': 'people',
  '🔢': 'numbers',
  '✏️': 'pencil',
  '✓': 'check',
  '✕': 'cross',
  'ℹ': 'info',
};

export const ICON_BASE = '/icons';
export const iconPath = (name: string) => `${ICON_BASE}/${name}.png`;
